site_name: Betty Programming Language
site_url: https://betty-lang.org

repo_url: https://github.com/betty-lang/betty
repo_name: betty-lang/betty

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/extra.css

extra_files:
  - CNAME

nav:
  - Introduction: 'index.md'
  - Data Types:
      - data-types/index.md
      - Number: data-types/number.md
      - String: data-types/string.md
      - Char: data-types/char.md
      - Boolean: data-types/boolean.md
      - List: data-types/list.md
      - None: data-types/none.md
  - Operators:
    - operators/index.md
    - Arithmetic: operators/arithmetic.md
    - Logical: operators/logical.md
    - Comparative: operators/comparative.md
    - Conditional: operators/conditional.md
    - Assignment: operators/assignment.md
    - Special: operators/special.md
  - Keywords:
    - keywords/index.md
    - Control Flow: keywords/control-flow.md
    - Functions: keywords/functions.md
    - Variables and Scope: keywords/variables-and-scope.md
  - Standard Library:
    - standard-library/index.md
    - Char: standard-library/char.md
    - Conversion: standard-library/conversion.md
    - IO: standard-library/io.md
    - List: standard-library/list.md
    - Math: standard-library/math.md
    - String: standard-library/string.md
  - Examples:
    - examples/index.md
    - "Example 1: Functions and Unary Operations": examples/functions-unary-operations.md
    - "Example 2: Implicit Conversions and Arithmetic": examples/implicit-conversions-arithmetic.md
    - "Example 3: Comments and Integer Division": examples/comments-int-division.md
    - "Example 4: Character Operations": examples/char-operations.md
    - "Example 5: Control Flow and Recursion": examples/control-flow-recursion.md
    - "Example 6: Loops and Conditionals": examples/loops-conditionals.md
    - "Example 7: Expression Evaluator": examples/expression-evaluator.md